use std::{fs, path::Path};

const APP_COMMANDS: &[&str] = &[
    "report_checker_event",
    "get_desktop_settings",
    "update_desktop_settings",
    "report_campus_ready",
    "refresh_campus_data",
    "get_dashboard_campus_data",
    "open_image_viewer",
    "get_dashboard_home_overview",
    "get_notification_inbox_snapshot",
    "activate_notification",
    "send_test_notification",
    "get_connected_service_status",
    "reset_desktop_identity",
    "open_lms_login",
    "create_mobile_pairing",
    "get_mobile_pairing_status",
    "approve_mobile_pairing",
    "list_mobile_sessions",
    "revoke_mobile_session",
    "get_remote_attendance_snapshot",
    "get_attendance_preferences",
    "update_attendance_preferences",
    "get_meal_preferences",
    "update_meal_preferences",
    "list_laundry_watches",
    "create_laundry_watch",
    "delete_laundry_watch",
    "list_laundry_queue",
    "join_laundry_queue",
    "leave_laundry_queue",
    "refresh_platform_sync",
];

const AUTOGENERATED_HEADER: &str = "# Automatically generated - DO NOT EDIT!";

fn prune_stale_command_permissions() {
    let directory = Path::new("permissions/autogenerated");
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let Some(command) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") || APP_COMMANDS.contains(&command)
        {
            continue;
        }

        let generated = fs::read_to_string(&path).is_ok_and(|contents| contents.starts_with(AUTOGENERATED_HEADER));
        if generated {
            fs::remove_file(&path).unwrap_or_else(|error| {
                panic!(
                    "failed to remove stale generated permission {}: {error}",
                    path.display()
                )
            });
        }
    }
}

fn main() {
    prune_stale_command_permissions();
    println!("cargo:rerun-if-env-changed=JUNGLE_BELL_DATA_API_URL");
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run Tauri build script");
}
