# 파일명은 `건의하기` 카테고리의 slug와 일치한다.
# https://docs.github.com/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms
title: "[기능 요청] "
body:
  - type: textarea
    id: idea
    attributes:
      label: 추가하거나 개선할 기능
      description: 원하는 기능과 기대하는 동작을 적어 주세요.
      placeholder: 어떤 기능이 있으면 좋을까요?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 필요한 이유
      description: 어떤 상황에서 도움이 되는지 적어 주세요.
    validations:
      required: false
