use std::{fs, path::PathBuf};

fn manifest_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn read(relative: &str) -> String {
    fs::read_to_string(manifest_path(relative)).unwrap_or_else(|error| panic!("failed to read {relative}: {error}"))
}

#[test]
fn native_image_viewer_surface_is_removed() {
    for relative in ["build.rs", "src/lib.rs", "src/commands.rs", "src/tray.rs"] {
        let source = read(relative);
        assert!(
            !source.contains("open_image_viewer"),
            "{relative} still exposes the image viewer"
        );
    }

    assert!(
        !read("capabilities/dashboard.json").contains("allow-open-image-viewer"),
        "dashboard capability still grants the removed image viewer command"
    );
    assert!(
        !manifest_path("capabilities/image-viewer.json").exists(),
        "the removed image viewer window still has a capability"
    );
    assert!(
        !manifest_path("permissions/autogenerated/open_image_viewer.toml").exists(),
        "the removed command still has a generated permission"
    );
}

#[test]
fn removed_viewer_does_not_keep_window_state_dependency() {
    assert!(
        !read("Cargo.toml").contains("tauri-plugin-window-state"),
        "window-state is only used by the removed image viewer"
    );
    assert!(
        !read("src/notification_inbox.rs").contains("image-viewer"),
        "notification badges still target the removed window"
    );
}
