use std::{fs, path::Path};

const APP_COMMANDS: &[&str] = &[
    "report_checker_event",
    "bootstrap_desktop_http_session",
    "get_desktop_settings",
    "check_desktop_update",
    "install_desktop_update",
    "update_desktop_settings",
    "open_log_folder",
    "get_notification_inbox_snapshot",
    "mark_notification_read",
    "mark_all_notifications_read",
    "activate_notification",
    "send_test_notification",
    "get_connected_service_status",
    "reset_desktop_identity",
    "open_lms_login",
    "refresh_platform_sync",
];

const AUTOGENERATED_HEADER: &str = "# Automatically generated - DO NOT EDIT!";

fn prune_stale_command_permissions() {
    let directory = Path::new("permissions/autogenerated");
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let Some(command) = path.file_stem().and_then(|stem| stem.to_str()) else {
            continue;
        };
        if path.extension().and_then(|extension| extension.to_str()) != Some("toml") || APP_COMMANDS.contains(&command)
        {
            continue;
        }

        let generated = fs::read_to_string(&path).is_ok_and(|contents| contents.starts_with(AUTOGENERATED_HEADER));
        if generated {
            fs::remove_file(&path).unwrap_or_else(|error| {
                panic!(
                    "failed to remove stale generated permission {}: {error}",
                    path.display()
                )
            });
        }
    }
}

fn required_data_api_origin() -> String {
    let value = std::env::var("JUNGLE_BELL_DATA_API_URL")
        .unwrap_or_else(|_| panic!("JUNGLE_BELL_DATA_API_URL is required to compile jungle-bell"));
    let origin = value.trim().trim_end_matches('/');
    if origin.is_empty() || !origin.starts_with("https://") {
        panic!("JUNGLE_BELL_DATA_API_URL must be a non-empty HTTPS origin");
    }

    let authority = &origin["https://".len()..];
    if authority.is_empty() || authority.contains(['/', '?', '#', '@']) || authority.chars().any(char::is_whitespace) {
        panic!("JUNGLE_BELL_DATA_API_URL must not contain credentials, a path, a query, or a fragment");
    }

    let tauri_config =
        fs::read_to_string("tauri.conf.json").unwrap_or_else(|error| panic!("failed to read tauri.conf.json: {error}"));
    if !tauri_config.contains(&format!(" {origin};")) {
        panic!("JUNGLE_BELL_DATA_API_URL must be explicitly allowed by the Tauri CSP");
    }
    origin.to_owned()
}

fn main() {
    prune_stale_command_permissions();
    println!("cargo:rerun-if-env-changed=JUNGLE_BELL_DATA_API_URL");
    let data_api_origin = required_data_api_origin();
    println!("cargo:rustc-env=JUNGLE_BELL_DATA_API_URL={data_api_origin}");
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run Tauri build script");
}
